package by.epam.zhalabkevich.my_telecom.controller.command;

public enum CommandName {
    AUTHORIZATION, NO_SUCH_COMMAND, EDIT_PROFILE, REGISTRATION, CREATE_USER, UPDATE_USER, LOGOUT,
    SHOW_TARIFFS, UPDATE_BALANCE, SHOW_USERS, ADD_NOTE, DELETE_NOTE, CHANGE_STATUS, CHANGE_BALANCE,
    DELETE_USER, DELETE_TARIFF, EDIT_TARIFF, ADD_TARIFF, SHOW_USER_TARIFF, LOCAL, PAYMENT, BLOCK, TARIFF_PAGINATION, STATISTIC,
    USER_PAGINATION, UPDATE_PASSWORD
}
