package by.epam.zhalabkevich.my_telecom.controller.command;

public enum CommandName {
    AUTHORIZATION, NO_SUCH_COMMAND, EDIT_PROFILE, REGISTRATION, LOGOUT,
    SHOW_TARIFFS, UPDATE_BALANCE, SHOW_USERS, ADD_NOTE, DELETE_NOTE, CHANGE_STATUS, CHANGE_BALANCE,
    DELETE_USER, DELETE_TARIFF, EDIT_TARIFF, ADD_TARIFF, SHOW_USER_TARIFF, LOCAL, PAYMENT, BLOCK, TARIFF_PAGINATION, STATISTIC,
    USER_PAGINATION, UPDATE_PASSWORD, UPDATE_PROMOTION, CREATE_PROMOTION, DELETE_PROMOTION, ADD_PROMOTION_TO_TARIFF, SHOW_PROMOTIONS,
    SHOW_USER_INFO, UPDATE_USER_INFO, GO_TO_PAGE, SHOW_USER_TARIFFS, STATISTICS
}
